// US States → Capitals (50 entries)
export const usStates = [
  { state: "Alabama", capital: "Montgomery" },
  { state: "Alaska", capital: "Juneau" },
  { state: "Arizona", capital: "Phoenix" },
  { state: "Arkansas", capital: "Little Rock" },
  { state: "California", capital: "Sacramento" },
  { state: "Colorado", capital: "Denver" },
  { state: "Connecticut", capital: "Hartford" },
  { state: "Delaware", capital: "Dover" },
  { state: "Florida", capital: "Tallahassee" },
  { state: "Georgia", capital: "Atlanta" },
  { state: "Hawaii", capital: "Honolulu" },
  { state: "Idaho", capital: "Boise" },
  { state: "Illinois", capital: "Springfield" },
  { state: "Indiana", capital: "Indianapolis" },
  { state: "Iowa", capital: "Des Moines" },
  { state: "Kansas", capital: "Topeka" },
  { state: "Kentucky", capital: "Frankfort" },
  { state: "Louisiana", capital: "Baton Rouge" },
  { state: "Maine", capital: "Augusta" },
  { state: "Maryland", capital: "Annapolis" },
  { state: "Massachusetts", capital: "Boston" },
  { state: "Michigan", capital: "Lansing" },
  { state: "Minnesota", capital: "Saint Paul" },
  { state: "Mississippi", capital: "Jackson" },
  { state: "Missouri", capital: "Jefferson City" },
  { state: "Montana", capital: "Helena" },
  { state: "Nebraska", capital: "Lincoln" },
  { state: "Nevada", capital: "Carson City" },
  { state: "New Hampshire", capital: "Concord" },
  { state: "New Jersey", capital: "Trenton" },
  { state: "New Mexico", capital: "Santa Fe" },
  { state: "New York", capital: "Albany" },
  { state: "North Carolina", capital: "Raleigh" },
  { state: "North Dakota", capital: "Bismarck" },
  { state: "Ohio", capital: "Columbus" },
  { state: "Oklahoma", capital: "Oklahoma City" },
  { state: "Oregon", capital: "Salem" },
  { state: "Pennsylvania", capital: "Harrisburg" },
  { state: "Rhode Island", capital: "Providence" },
  { state: "South Carolina", capital: "Columbia" },
  { state: "South Dakota", capital: "Pierre" },
  { state: "Tennessee", capital: "Nashville" },
  { state: "Texas", capital: "Austin" },
  { state: "Utah", capital: "Salt Lake City" },
  { state: "Vermont", capital: "Montpelier" },
  { state: "Virginia", capital: "Richmond" },
  { state: "Washington", capital: "Olympia" },
  { state: "West Virginia", capital: "Charleston" },
  { state: "Wisconsin", capital: "Madison" },
  { state: "Wyoming", capital: "Cheyenne" },
];

// Countries → Capitals (~100 entries)
export const countries = [
  { country: "Afghanistan", capital: "Kabul" },
  { country: "Albania", capital: "Tirana" },
  { country: "Algeria", capital: "Algiers" },
  { country: "Argentina", capital: "Buenos Aires" },
  { country: "Armenia", capital: "Yerevan" },
  { country: "Australia", capital: "Canberra" },
  { country: "Austria", capital: "Vienna" },
  { country: "Azerbaijan", capital: "Baku" },
  { country: "Bangladesh", capital: "Dhaka" },
  { country: "Belarus", capital: "Minsk" },
  { country: "Belgium", capital: "Brussels" },
  { country: "Bolivia", capital: "Sucre" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo" },
  { country: "Brazil", capital: "Brasília" },
  { country: "Bulgaria", capital: "Sofia" },
  { country: "Cambodia", capital: "Phnom Penh" },
  { country: "Canada", capital: "Ottawa" },
  { country: "Chile", capital: "Santiago" },
  { country: "China", capital: "Beijing" },
  { country: "Colombia", capital: "Bogotá" },
  { country: "Croatia", capital: "Zagreb" },
  { country: "Cuba", capital: "Havana" },
  { country: "Czech Republic", capital: "Prague" },
  { country: "Denmark", capital: "Copenhagen" },
  { country: "Ecuador", capital: "Quito" },
  { country: "Egypt", capital: "Cairo" },
  { country: "Ethiopia", capital: "Addis Ababa" },
  { country: "Finland", capital: "Helsinki" },
  { country: "France", capital: "Paris" },
  { country: "Georgia", capital: "Tbilisi" },
  { country: "Germany", capital: "Berlin" },
  { country: "Ghana", capital: "Accra" },
  { country: "Greece", capital: "Athens" },
  { country: "Guatemala", capital: "Guatemala City" },
  { country: "Hungary", capital: "Budapest" },
  { country: "Iceland", capital: "Reykjavik" },
  { country: "India", capital: "New Delhi" },
  { country: "Indonesia", capital: "Jakarta" },
  { country: "Iran", capital: "Tehran" },
  { country: "Iraq", capital: "Baghdad" },
  { country: "Ireland", capital: "Dublin" },
  { country: "Israel", capital: "Jerusalem" },
  { country: "Italy", capital: "Rome" },
  { country: "Japan", capital: "Tokyo" },
  { country: "Jordan", capital: "Amman" },
  { country: "Kazakhstan", capital: "Astana" },
  { country: "Kenya", capital: "Nairobi" },
  { country: "Kuwait", capital: "Kuwait City" },
  { country: "Laos", capital: "Vientiane" },
  { country: "Latvia", capital: "Riga" },
  { country: "Lebanon", capital: "Beirut" },
  { country: "Libya", capital: "Tripoli" },
  { country: "Lithuania", capital: "Vilnius" },
  { country: "Malaysia", capital: "Kuala Lumpur" },
  { country: "Mexico", capital: "Mexico City" },
  { country: "Moldova", capital: "Chișinău" },
  { country: "Mongolia", capital: "Ulaanbaatar" },
  { country: "Morocco", capital: "Rabat" },
  { country: "Mozambique", capital: "Maputo" },
  { country: "Myanmar", capital: "Naypyidaw" },
  { country: "Nepal", capital: "Kathmandu" },
  { country: "Netherlands", capital: "Amsterdam" },
  { country: "New Zealand", capital: "Wellington" },
  { country: "Nigeria", capital: "Abuja" },
  { country: "North Korea", capital: "Pyongyang" },
  { country: "Norway", capital: "Oslo" },
  { country: "Pakistan", capital: "Islamabad" },
  { country: "Panama", capital: "Panama City" },
  { country: "Paraguay", capital: "Asunción" },
  { country: "Peru", capital: "Lima" },
  { country: "Philippines", capital: "Manila" },
  { country: "Poland", capital: "Warsaw" },
  { country: "Portugal", capital: "Lisbon" },
  { country: "Romania", capital: "Bucharest" },
  { country: "Russia", capital: "Moscow" },
  { country: "Saudi Arabia", capital: "Riyadh" },
  { country: "Senegal", capital: "Dakar" },
  { country: "Serbia", capital: "Belgrade" },
  { country: "Singapore", capital: "Singapore" },
  { country: "Slovakia", capital: "Bratislava" },
  { country: "Somalia", capital: "Mogadishu" },
  { country: "South Africa", capital: "Pretoria" },
  { country: "South Korea", capital: "Seoul" },
  { country: "Spain", capital: "Madrid" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte" },
  { country: "Sudan", capital: "Khartoum" },
  { country: "Sweden", capital: "Stockholm" },
  { country: "Switzerland", capital: "Bern" },
  { country: "Syria", capital: "Damascus" },
  { country: "Taiwan", capital: "Taipei" },
  { country: "Tanzania", capital: "Dodoma" },
  { country: "Thailand", capital: "Bangkok" },
  { country: "Tunisia", capital: "Tunis" },
  { country: "Turkey", capital: "Ankara" },
  { country: "Uganda", capital: "Kampala" },
  { country: "Ukraine", capital: "Kyiv" },
  { country: "United Arab Emirates", capital: "Abu Dhabi" },
  { country: "United Kingdom", capital: "London" },
  { country: "United States", capital: "Washington D.C." },
  { country: "Uruguay", capital: "Montevideo" },
  { country: "Uzbekistan", capital: "Tashkent" },
  { country: "Venezuela", capital: "Caracas" },
  { country: "Vietnam", capital: "Hanoi" },
  { country: "Yemen", capital: "Sanaa" },
  { country: "Zambia", capital: "Lusaka" },
  { country: "Zimbabwe", capital: "Harare" },
];

// Countries → Continents (same countries as above)
export const continents = [
  { country: "Afghanistan", continent: "Asia" },
  { country: "Albania", continent: "Europe" },
  { country: "Algeria", continent: "Africa" },
  { country: "Argentina", continent: "South America" },
  { country: "Armenia", continent: "Asia" },
  { country: "Australia", continent: "Oceania" },
  { country: "Austria", continent: "Europe" },
  { country: "Azerbaijan", continent: "Asia" },
  { country: "Bangladesh", continent: "Asia" },
  { country: "Belarus", continent: "Europe" },
  { country: "Belgium", continent: "Europe" },
  { country: "Bolivia", continent: "South America" },
  { country: "Bosnia and Herzegovina", continent: "Europe" },
  { country: "Brazil", continent: "South America" },
  { country: "Bulgaria", continent: "Europe" },
  { country: "Cambodia", continent: "Asia" },
  { country: "Canada", continent: "North America" },
  { country: "Chile", continent: "South America" },
  { country: "China", continent: "Asia" },
  { country: "Colombia", continent: "South America" },
  { country: "Croatia", continent: "Europe" },
  { country: "Cuba", continent: "North America" },
  { country: "Czech Republic", continent: "Europe" },
  { country: "Denmark", continent: "Europe" },
  { country: "Ecuador", continent: "South America" },
  { country: "Egypt", continent: "Africa" },
  { country: "Ethiopia", continent: "Africa" },
  { country: "Finland", continent: "Europe" },
  { country: "France", continent: "Europe" },
  { country: "Georgia", continent: "Asia" },
  { country: "Germany", continent: "Europe" },
  { country: "Ghana", continent: "Africa" },
  { country: "Greece", continent: "Europe" },
  { country: "Guatemala", continent: "North America" },
  { country: "Hungary", continent: "Europe" },
  { country: "Iceland", continent: "Europe" },
  { country: "India", continent: "Asia" },
  { country: "Indonesia", continent: "Asia" },
  { country: "Iran", continent: "Asia" },
  { country: "Iraq", continent: "Asia" },
  { country: "Ireland", continent: "Europe" },
  { country: "Israel", continent: "Asia" },
  { country: "Italy", continent: "Europe" },
  { country: "Japan", continent: "Asia" },
  { country: "Jordan", continent: "Asia" },
  { country: "Kazakhstan", continent: "Asia" },
  { country: "Kenya", continent: "Africa" },
  { country: "Kuwait", continent: "Asia" },
  { country: "Laos", continent: "Asia" },
  { country: "Latvia", continent: "Europe" },
  { country: "Lebanon", continent: "Asia" },
  { country: "Libya", continent: "Africa" },
  { country: "Lithuania", continent: "Europe" },
  { country: "Malaysia", continent: "Asia" },
  { country: "Mexico", continent: "North America" },
  { country: "Moldova", continent: "Europe" },
  { country: "Mongolia", continent: "Asia" },
  { country: "Morocco", continent: "Africa" },
  { country: "Mozambique", continent: "Africa" },
  { country: "Myanmar", continent: "Asia" },
  { country: "Nepal", continent: "Asia" },
  { country: "Netherlands", continent: "Europe" },
  { country: "New Zealand", continent: "Oceania" },
  { country: "Nigeria", continent: "Africa" },
  { country: "North Korea", continent: "Asia" },
  { country: "Norway", continent: "Europe" },
  { country: "Pakistan", continent: "Asia" },
  { country: "Panama", continent: "North America" },
  { country: "Paraguay", continent: "South America" },
  { country: "Peru", continent: "South America" },
  { country: "Philippines", continent: "Asia" },
  { country: "Poland", continent: "Europe" },
  { country: "Portugal", continent: "Europe" },
  { country: "Romania", continent: "Europe" },
  { country: "Russia", continent: "Europe" },
  { country: "Saudi Arabia", continent: "Asia" },
  { country: "Senegal", continent: "Africa" },
  { country: "Serbia", continent: "Europe" },
  { country: "Singapore", continent: "Asia" },
  { country: "Slovakia", continent: "Europe" },
  { country: "Somalia", continent: "Africa" },
  { country: "South Africa", continent: "Africa" },
  { country: "South Korea", continent: "Asia" },
  { country: "Spain", continent: "Europe" },
  { country: "Sri Lanka", continent: "Asia" },
  { country: "Sudan", continent: "Africa" },
  { country: "Sweden", continent: "Europe" },
  { country: "Switzerland", continent: "Europe" },
  { country: "Syria", continent: "Asia" },
  { country: "Taiwan", continent: "Asia" },
  { country: "Tanzania", continent: "Africa" },
  { country: "Thailand", continent: "Asia" },
  { country: "Tunisia", continent: "Africa" },
  { country: "Turkey", continent: "Asia" },
  { country: "Uganda", continent: "Africa" },
  { country: "Ukraine", continent: "Europe" },
  { country: "United Arab Emirates", continent: "Asia" },
  { country: "United Kingdom", continent: "Europe" },
  { country: "United States", continent: "North America" },
  { country: "Uruguay", continent: "South America" },
  { country: "Uzbekistan", continent: "Asia" },
  { country: "Venezuela", continent: "South America" },
  { country: "Vietnam", continent: "Asia" },
  { country: "Yemen", continent: "Asia" },
  { country: "Zambia", continent: "Africa" },
  { country: "Zimbabwe", continent: "Africa" },
];
